@startuml

actor ":Usuario" as usuario
participant ":Inicio" as inicio
participant ":ServletRecordatorio" as servletRecordatorio
participant ":ServletNotificacion" as servletNotificacion
participant ":ServletResumenFinanciero" as servletResumen
participant ":ServicioResumenFinanciero" as servicioResumen
participant ":ServletDocumentoPDF" as servletDocumentoPDF
participant ":DAODocumentoPDF" as daoDocumentoPDF
participant ":ControladorDeudas" as controladorDeudas
participant ":ServicioMovimientos" as servicioMovimientos
participant ":Gasto" as gasto
participant ":Ingreso" as ingreso
participant ":Cartera" as cartera
participant ":DeudaPrestamo" as deudaPrestamo
participant ":ResumenFinanciero" as resumen
participant ":DocumentoPDF" as documentoPDF
participant ":Recordatorio" as recordatorio
participant ":DAOMovimiento" as daoMovimiento
participant ":DAOCartera" as carteraDAO
participant ":DeudaPrestamoDAO" as deudaPrestamoDAO
participant ":ResumenFinancieroDAO" as resumenDAO
participant ":DAORecordatorio" as DAOrecordatorio

== Registrar Ingreso y Gasto ==
usuario -> inicio: seleccionarRegistrarIngreso()
inicio -> servicioMovimientos: registrarIngreso(monto, descripcion, categoria, nombreCartera)
servicioMovimientos -> daoMovimiento: crear(ingreso)
daoMovimiento --> servicioMovimientos: ingresoPersistido
servicioMovimientos -> carteraDAO: obtenerOCrear(nombreCartera, tipoPreferido)
carteraDAO --> servicioMovimientos: cartera
servicioMovimientos -> cartera: actualizarCartera(monto)
servicioMovimientos -> carteraDAO: actualizar(cartera)
servicioMovimientos --> inicio: ingresoRegistrado
inicio --> usuario: mostrarConfirmacionIngreso


usuario -> inicio: seleccionarRegistrarGasto()
inicio -> servicioMovimientos: registrarGasto(monto, descripcion, categoria, nombreCartera)
servicioMovimientos -> daoMovimiento: crear(gasto)
daoMovimiento --> servicioMovimientos: gastoPersistido
servicioMovimientos -> carteraDAO: obtenerOCrear(nombreCartera, tipoPreferido)
carteraDAO --> servicioMovimientos: cartera
servicioMovimientos -> cartera: actualizarCartera(-monto)
servicioMovimientos -> carteraDAO: actualizar(cartera)
servicioMovimientos --> inicio: gastoRegistrado
inicio --> usuario: mostrarConfirmacionGasto

== Consultar Totales de Movimientos ==
usuario -> inicio: solicitarTotales()
inicio -> servicioMovimientos: obtenerIngresosTotales()
servicioMovimientos -> daoMovimiento: sumIngresos()
daoMovimiento --> servicioMovimientos: totalIngresos
servicioMovimientos --> inicio: totalIngresos
inicio -> servicioMovimientos: obtenerGastosTotales()
servicioMovimientos -> daoMovimiento: sumGastos()
daoMovimiento --> servicioMovimientos: totalGastos
servicioMovimientos --> inicio: totalGastos
inicio -> servicioMovimientos: obtenerSaldoActualTotal()
servicioMovimientos -> carteraDAO: sumSaldoActual()
carteraDAO --> servicioMovimientos: saldoTotal
servicioMovimientos --> inicio: saldoTotal
inicio --> usuario: mostrarTotales(inIngresos, inGastos, saldo)

== Registrar Deuda y abonar a Deuda==
usuario -> inicio: seleccionarRegistrarDeuda()
inicio -> controladorDeudas: registrarDeuda(monto, acreedor)
controladorDeudas -> deudaPrestamoDAO: crear(deudaPrestamo)

usuario -> inicio: seleccionarAbonarDeuda()
inicio -> controladorDeudas: abonarADeuda(idDeuda, monto)
controladorDeudas -> deudaPrestamoDAO: buscarPorID(idDeuda)
controladorDeudas -> deudaPrestamo: registrarAbono(monto)
controladorDeudas -> deudaPrestamoDAO: actualizar(deudaPrestamo)

controladorDeudas -> servicioMovimientos: registrarGasto(monto, "Abono deuda", "Deudas")
servicioMovimientos -> daoMovimiento: crear(gasto)

== Generar Resumen Financiero ==
usuario -> inicio: solicitarResumenMensual()
inicio -> servletResumen: subirArchivo()
servletResumen -> daoDocumentoPDF: crear(documento)
servletResumen -> servletResumen: procesarInformacion(): List<String>
servletResumen -> servicioResumen: extraerFecha(textoPDF: String)
servicioResumen --> servletResumen: fecha
servletResumen -> servicioResumen: extraerMonto(textoPDF: String)
servicioResumen --> servletResumen: monto
servletResumen -> servletResumen: registrarResumenFinanciero(informacionProcesada: List<String>)
servletResumen -> resumenDAO: crear(resumen)
usuario -> inicio: solicitarResumenes()
inicio -> servletResumen: obtenerResumenesFinancieros()
servletResumen -> resumenDAO: listar()
resumenDAO --> servletResumen: List<ResumenFinanciero>
servletResumen -> servletDocumentoPDF: descargarDocumentoPDF(): void

== Gestionar Recordatorios ==

== Crear Recordatorio ==

usuario -> inicio: seleccionarCrearRecordatorio()
inicio -> servletRecordatorio: solicitarFormularioNuevoRecordatorio()
servletRecordatorio -> servletRecordatorio: mostrarFormulario(recordatorio)
servletRecordatorio --> inicio: VistaFormularioRecordatorio.jsp
inicio --> usuario: mostrarFormulario()

usuario -> inicio: completarDatosRecordatorio()
inicio -> servletRecordatorio: enviarDatosRecordatorio()
servletRecordatorio -> servletRecordatorio: construirRecordatorioDesdeRequest()
servletRecordatorio -> servletRecordatorio: crearRecordatorio()
servletRecordatorio -> recordatorio: new Recordatorio()
servletRecordatorio -> DAOrecordatorio: crear(recordatorio)
servletRecordatorio --> inicio: confirmarCreacionExitosa()
inicio --> usuario: mostrarMensajeExito()

== Listar Recordatorios ==
usuario -> inicio: solicitarListaRecordatorios()
inicio -> servletRecordatorio: obtenerRecordatorios()
servletRecordatorio -> servletRecordatorio: listarRecordatorios()
servletRecordatorio -> DAOrecordatorio: listar()
DAOrecordatorio --> servletRecordatorio: List<Recordatorio>
servletRecordatorio --> inicio: VistaRecordatorios.jsp
inicio --> usuario: mostrarListaRecordatorios()

== Editar Recordatorio ==
usuario -> inicio: seleccionarEditarRecordatorio(id)
inicio -> servletRecordatorio: solicitarFormularioEdicion()
servletRecordatorio -> servletRecordatorio: mostrarFormularioEditar()
servletRecordatorio -> DAOrecordatorio: buscarPorId(id)
DAOrecordatorio --> servletRecordatorio: Recordatorio
servletRecordatorio -> servletRecordatorio: mostrarFormulario(recordatorio)
servletRecordatorio --> inicio: VistaFormularioRecordatorio.jsp
inicio --> usuario: mostrarFormularioConDatos()

usuario -> inicio: modificarDatosRecordatorio()
inicio -> servletRecordatorio: enviarDatosModificados()
servletRecordatorio -> servletRecordatorio: construirRecordatorioDesdeRequest()
servletRecordatorio -> servletRecordatorio: actualizarRecordatorio()
servletRecordatorio -> DAOrecordatorio: actualizar(recordatorio)
servletRecordatorio --> inicio: confirmarActualizacion()
inicio --> usuario: mostrarMensajeExito()

== Eliminar Recordatorio ==
usuario -> inicio: solicitarEliminarRecordatorio(id)
inicio -> servletRecordatorio: eliminarRecordatorio()
servletRecordatorio -> servletRecordatorio: borrarRecordatorio()
servletRecordatorio -> DAOrecordatorio: borrar(idRecordatorio)
servletRecordatorio --> inicio: confirmarEliminacion()
inicio --> usuario: mostrarMensajeExito()

== Obtener Notificaciones ==
usuario -> servletNotificacion: solicitarNotificaciones()
servletNotificacion -> DAOrecordatorio: listarActivos()
DAOrecordatorio --> servletNotificacion: List<Recordatorio>

loop para cada recordatorio
    servletNotificacion -> recordatorio: obtenerFechaVencimiento(hoy)
    recordatorio -> recordatorio: calcularProximaFechaVencimiento(desde)
    recordatorio --> servletNotificacion: Optional<LocalDate>
end

servletNotificacion -> servletNotificacion: procesarNotificaciones()
servletNotificacion --> usuario: notificaciones JSON


@enduml