@startuml
== Generar Resumen Financiero ==
actor ":Usuario" as usuario

usuario -> inicio: solicitarResumenMensual()
inicio -> servletResumen: subirArchivo()
servletResumen -> documentoPDF: new DocumentoPDF(): DocumentoPDF
servletResumen -> daoDocumentoPDF: crear(documento: DocumentoPDF)
servletResumen -> servletResumen: procesarInformacion(): String
servletResumen -> servicioResumen: extraerFecha(textoPDF: String)
servicioResumen --> servletResumen: fecha
servletResumen -> servicioResumen: extraerMonto(textoPDF: String)
servicioResumen --> servletResumen: monto
servletResumen -> servletResumen: registrarResumenFinanciero(informacionProcesada: List<String>)
servletResumen -> ResumenFinanciero: new ResumenFinanciero(): ResumenFinanciero
servletResumen -> resumenDAO: crear(resumen: ResumenFinanciero)
usuario -> inicio: solicitarResumenes()
inicio -> servletResumen: obtenerResumenesFinancieros()
servletResumen -> resumenDAO: listar()
resumenDAO --> servletResumen: List<ResumenFinanciero>
servletResumen -> servletDocumentoPDF: descargarDocumentoPDF(): void

@enduml